spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:templates/
  web:
    resources:
      static-locations: classpath:static/
      cache:
        period: 0


logging:
  config: classpath:static/log/logback.xml
